# Generated by Django 4.2.7 on 2025-07-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snake_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pics/default.svg", upload_to="profile_pics/"
            ),
        ),
    ]
