# Generated by Django 4.2.7 on 2025-07-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snake_app", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="allow_friend_requests",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="allow_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="control_scheme",
            field=models.CharField(default="default", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="enable_subtitles",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="game_difficulty",
            field=models.CharField(default="medium", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="invert_y_axis",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="master_volume",
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name="customuser",
            name="motion_blur",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_visibility",
            field=models.CharField(default="public", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.CharField(default="eu", max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="share_analytics",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="share_gameplay_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_game_activity",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_online_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="show_tutorials",
            field=models.BooleanField(default=False),
        ),
    ]
